# DANTE SOCKS5 Proxy on Ubuntu
---
- hosts: all
  become: true
  vars_files: [vars.yml]

  tasks:
  - name: Upgrade apt packages
    apt:
      name: "*"
      state: latest

  - name: Install Dante
    apt: name=dante-server state=latest

  - name: Copy Dante config file
    copy:
      src: ./files/danted.conf
      dest: /etc/danted.conf
      owner: root
      group: root
      mode: '0644'

  - name: UFW Allow SSH connections
    ufw:
      rule: allow
      name: OpenSSH

  - name: UFW Allow proxy port
    ufw:
      rule: allow
      port: 1080

  - name: UFW Deny all other incoming traffic by default
    ufw:
      state: enabled
      policy: deny
      direction: incoming

  - name: Add Dante user
    user:
      name: "{{ username }}"
      password: "{{ password }}"
      system: true
      create_home: false
      shell: /bin/false

  - name: Restart Dante service
    systemd:
      state: restarted
      daemon_reload: true
      name: danted.service

  - name: Reboot server
    reboot:
